/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { lazy } from 'react';
export const InstallAppButtonMap = {
  exchange2013calendar: lazy(() => import("./exchange2013calendar/components/InstallAppButton")),
  exchange2016calendar: lazy(() => import("./exchange2016calendar/components/InstallAppButton")),
  office365video: lazy(() => import("./office365video/components/InstallAppButton")),
  vital: lazy(() => import("./vital/components/InstallAppButton")),
};
export const AppSettingsComponentsMap = {
  "general-app-settings": lazy(
    () => import("./templates/general-app-settings/components/AppSettingsInterface")
  ),
  weather_in_your_calendar: lazy(
    () => import("./weather_in_your_calendar/components/AppSettingsInterface")
  ),
  zapier: lazy(() => import("./zapier/components/AppSettingsInterface")),
};
export const EventTypeAddonMap = {
  alby: lazy(() => import("./alby/components/EventTypeAppCardInterface")),
  basecamp3: lazy(() => import("./basecamp3/components/EventTypeAppCardInterface")),
  btcpayserver: lazy(() => import("./btcpayserver/components/EventTypeAppCardInterface")),
  closecom: lazy(() => import("./closecom/components/EventTypeAppCardInterface")),
  databuddy: lazy(() => import("./databuddy/components/EventTypeAppCardInterface")),
  fathom: lazy(() => import("./fathom/components/EventTypeAppCardInterface")),
  ga4: lazy(() => import("./ga4/components/EventTypeAppCardInterface")),
  giphy: lazy(() => import("./giphy/components/EventTypeAppCardInterface")),
  gtm: lazy(() => import("./gtm/components/EventTypeAppCardInterface")),
  hitpay: lazy(() => import("./hitpay/components/EventTypeAppCardInterface")),
  hubspot: lazy(() => import("./hubspot/components/EventTypeAppCardInterface")),
  insihts: lazy(() => import("./insihts/components/EventTypeAppCardInterface")),
  matomo: lazy(() => import("./matomo/components/EventTypeAppCardInterface")),
  metapixel: lazy(() => import("./metapixel/components/EventTypeAppCardInterface")),
  "mock-payment-app": lazy(() => import("./mock-payment-app/components/EventTypeAppCardInterface")),
  paypal: lazy(() => import("./paypal/components/EventTypeAppCardInterface")),
  "pipedrive-crm": lazy(() => import("./pipedrive-crm/components/EventTypeAppCardInterface")),
  plausible: lazy(() => import("./plausible/components/EventTypeAppCardInterface")),
  posthog: lazy(() => import("./posthog/components/EventTypeAppCardInterface")),
  qr_code: lazy(() => import("./qr_code/components/EventTypeAppCardInterface")),
  salesforce: lazy(() => import("./salesforce/components/EventTypeAppCardInterface")),
  stripepayment: lazy(() => import("./stripepayment/components/EventTypeAppCardInterface")),
  "booking-pages-tag": lazy(
    () => import("./templates/booking-pages-tag/components/EventTypeAppCardInterface")
  ),
  "event-type-app-card": lazy(
    () => import("./templates/event-type-app-card/components/EventTypeAppCardInterface")
  ),
  twipla: lazy(() => import("./twipla/components/EventTypeAppCardInterface")),
  umami: lazy(() => import("./umami/components/EventTypeAppCardInterface")),
  "zoho-bigin": lazy(() => import("./zoho-bigin/components/EventTypeAppCardInterface")),
  zohocrm: lazy(() => import("./zohocrm/components/EventTypeAppCardInterface")),
};
export const EventTypeSettingsMap = {
  alby: lazy(() => import("./alby/components/EventTypeAppSettingsInterface")),
  basecamp3: lazy(() => import("./basecamp3/components/EventTypeAppSettingsInterface")),
  btcpayserver: lazy(() => import("./btcpayserver/components/EventTypeAppSettingsInterface")),
  databuddy: lazy(() => import("./databuddy/components/EventTypeAppSettingsInterface")),
  fathom: lazy(() => import("./fathom/components/EventTypeAppSettingsInterface")),
  ga4: lazy(() => import("./ga4/components/EventTypeAppSettingsInterface")),
  giphy: lazy(() => import("./giphy/components/EventTypeAppSettingsInterface")),
  gtm: lazy(() => import("./gtm/components/EventTypeAppSettingsInterface")),
  hitpay: lazy(() => import("./hitpay/components/EventTypeAppSettingsInterface")),
  metapixel: lazy(() => import("./metapixel/components/EventTypeAppSettingsInterface")),
  paypal: lazy(() => import("./paypal/components/EventTypeAppSettingsInterface")),
  plausible: lazy(() => import("./plausible/components/EventTypeAppSettingsInterface")),
  qr_code: lazy(() => import("./qr_code/components/EventTypeAppSettingsInterface")),
  stripepayment: lazy(() => import("./stripepayment/components/EventTypeAppSettingsInterface")),
};
